# Generated by Django 5.1.7 on 2025-05-22 13:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_role_chartofaccounts_company_companyuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_name', models.CharField(max_length=255)),
                ('contract_duration', models.CharField(max_length=100)),
                ('expected_cargo', models.TextField(max_length=255)),
                ('contract_unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('contract_start', models.DateField()),
                ('contract_client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
            ],
        ),
        migrations.CreateModel(
            name='GeneralCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consignment_no', models.CharField(max_length=255)),
                ('kra_no', models.CharField(max_length=255)),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('no_bags', models.PositiveIntegerField()),
                ('units_measure', models.CharField(max_length=50)),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status_one', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyuser')),
            ],
        ),
        migrations.CreateModel(
            name='CargoItemRelease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transporter', models.CharField(blank=True, max_length=255, null=True)),
                ('no_bags', models.PositiveIntegerField()),
                ('net_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gross_weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyuser')),
                ('general_cargo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.generalcargo')),
            ],
        ),
        migrations.CreateModel(
            name='OperationTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_operation', models.CharField(max_length=255)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.company')),
                ('company_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.companyuser')),
                ('price_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.priceset')),
            ],
        ),
    ]
